#!/bin/bash

case "$1" in 
	create)
		if [ -z $2 ]; then
			echo "Argument databaseName is missing."
			exit 1;
		fi
		mysql --login-path=local -e "create database $2"
		echo "Database $2 successful created!"
		;;
	list)
		mysql --login-path=local -e "show databases"
		;;
	drop)
		if [ -z $2 ]; then
			echo "Argument databaseName is missing."
			exit 1;
		fi
		mysql --login-path=local -e "drop database $2"
		echo "Database $2 dropped"
		;;
	tables)
		if [ -z $2 ]; then
			echo "Database name is missing. Example: db tables [databaseName]"
			exit 1;
		fi
		mysql --login-path=local -e "use $2; show tables;"
		;;
	describe)
		if [ -z $2 ]; then
			echo "Argument for database table missing. Example: [database].[table]"
			exit 1;
		fi
		mysql --login-path=local -e "describe $2"
		;;
	login)
		mysql --login-path=local $2
		;;
	*)
		echo "Options: create, list, drop, describe, login"
		;;
esac
